# Generated by Django 2.2 on 2020-10-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100)),
                ('Image', models.FileField(blank=True, upload_to='images/dataImage')),
                ('Date', models.CharField(max_length=100)),
                ('Time', models.CharField(blank=True, max_length=100)),
                ('realuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_User.RealUser')),
            ],
        ),
    ]
