# Generated by Django 2.2 on 2020-10-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='realuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_User.RealUser'),
        ),
    ]
